// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function ConnectSSH(arg1) {
  return window['go']['main']['App']['ConnectSSH'](arg1);
}

export function DeleteContainer(arg1) {
  return window['go']['main']['App']['DeleteContainer'](arg1);
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function DisconnectSSH(arg1) {
  return window['go']['main']['App']['DisconnectSSH'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetContainers() {
  return window['go']['main']['App']['GetContainers']();
}

export function GetDockerStats() {
  return window['go']['main']['App']['GetDockerStats']();
}

export function GetGitHubStats(arg1) {
  return window['go']['main']['App']['GetGitHubStats'](arg1);
}

export function GetLastData() {
  return window['go']['main']['App']['GetLastData']();
}

export function GetServerMetrics(arg1) {
  return window['go']['main']['App']['GetServerMetrics'](arg1);
}

export function GetServerPing(arg1) {
  return window['go']['main']['App']['GetServerPing'](arg1);
}

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function SSHResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['SSHResize'](arg1, arg2, arg3);
}

export function SSHWrite(arg1, arg2) {
  return window['go']['main']['App']['SSHWrite'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveSSHKey(arg1, arg2) {
  return window['go']['main']['App']['SaveSSHKey'](arg1, arg2);
}

export function SaveServer(arg1) {
  return window['go']['main']['App']['SaveServer'](arg1);
}

export function SignOut() {
  return window['go']['main']['App']['SignOut']();
}

export function StartContainer(arg1) {
  return window['go']['main']['App']['StartContainer'](arg1);
}

export function StartDeviceFlow() {
  return window['go']['main']['App']['StartDeviceFlow']();
}

export function StopContainer(arg1) {
  return window['go']['main']['App']['StopContainer'](arg1);
}

export function StreamContainerLogs(arg1, arg2) {
  return window['go']['main']['App']['StreamContainerLogs'](arg1, arg2);
}
