// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDockerStats() {
  return window['go']['main']['App']['GetDockerStats']();
}

export function GetGitHubStats(arg1) {
  return window['go']['main']['App']['GetGitHubStats'](arg1);
}

export function GetLastData() {
  return window['go']['main']['App']['GetLastData']();
}

export function GetServerPing(arg1) {
  return window['go']['main']['App']['GetServerPing'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SignOut() {
  return window['go']['main']['App']['SignOut']();
}

export function StartOAuthFlow(arg1, arg2) {
  return window['go']['main']['App']['StartOAuthFlow'](arg1, arg2);
}
