// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteContainer(arg1:string):Promise<void>;

export function GetConfig():Promise<main.Config>;

export function GetContainers():Promise<Array<main.ContainerInfo>>;

export function GetDockerStats():Promise<main.DockerStats>;

export function GetGitHubStats(arg1:string):Promise<main.GitHubStats>;

export function GetLastData():Promise<main.WidgetData>;

export function GetServerPing(arg1:string):Promise<main.ServerStatus>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SignOut():Promise<void>;

export function StartContainer(arg1:string):Promise<void>;

export function StartOAuthFlow(arg1:string,arg2:string):Promise<void>;

export function StopContainer(arg1:string):Promise<void>;

export function StreamContainerLogs(arg1:string,arg2:number):Promise<string>;
