// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteContainer(arg1) {
  return window['go']['main']['App']['DeleteContainer'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetContainers() {
  return window['go']['main']['App']['GetContainers']();
}

export function GetDockerStats() {
  return window['go']['main']['App']['GetDockerStats']();
}

export function GetGitHubStats(arg1) {
  return window['go']['main']['App']['GetGitHubStats'](arg1);
}

export function GetLastData() {
  return window['go']['main']['App']['GetLastData']();
}

export function GetServerPing(arg1) {
  return window['go']['main']['App']['GetServerPing'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SignOut() {
  return window['go']['main']['App']['SignOut']();
}

export function StartContainer(arg1) {
  return window['go']['main']['App']['StartContainer'](arg1);
}

export function StartOAuthFlow(arg1, arg2) {
  return window['go']['main']['App']['StartOAuthFlow'](arg1, arg2);
}

export function StopContainer(arg1) {
  return window['go']['main']['App']['StopContainer'](arg1);
}

export function StreamContainerLogs(arg1, arg2) {
  return window['go']['main']['App']['StreamContainerLogs'](arg1, arg2);
}
