// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppVersion():Promise<string>;

export function ConnectSSH(arg1:string):Promise<string>;

export function DeleteContainer(arg1:string):Promise<void>;

export function DeleteServer(arg1:string):Promise<void>;

export function DisconnectSSH(arg1:string):Promise<void>;

export function GetConfig():Promise<main.Config>;

export function GetContainers():Promise<Array<main.ContainerInfo>>;

export function GetDockerStats():Promise<main.DockerStats>;

export function GetGitHubStats(arg1:string):Promise<main.GitHubStats>;

export function GetLastData():Promise<main.AppData>;

export function GetServerMetrics(arg1:string):Promise<main.ServerMetrics>;

export function GetServerPing(arg1:string):Promise<main.ServerStatus>;

export function GetServers():Promise<Array<main.ServerConfig>>;

export function SSHResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SSHWrite(arg1:string,arg2:string):Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SaveSSHKey(arg1:string,arg2:string):Promise<string>;

export function SaveServer(arg1:main.ServerConfig):Promise<string>;

export function SignOut():Promise<void>;

export function StartContainer(arg1:string):Promise<void>;

export function StartDeviceFlow():Promise<void>;

export function StopContainer(arg1:string):Promise<void>;

export function StreamContainerLogs(arg1:string,arg2:number):Promise<string>;
